dragon: sensors: Set Proximity as Wake up sensor.
To be compliant with Android API, default proximity sensor must be a
wake up sensor.
The EC is not yet enabled to wake the AP up when there is a change in
proximity reading.

BUG=chrome-os-partner:44782
TEST=android.hardware.cts.SensorTest#testWakeUpFlags pass. Before we
would hit the assertion:
...AssertionFailedError: No wake-up proximity sensors implemented

Change-Id: I61442a49f41e07b7f2330f2d2e74fd8d82c3c918
Signed-off-by: Gwendal Grignou <gwendal@google.com>